apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.deployment.replaceAll('component:default/','').replaceAll(r/-deployment$/g, '')}}-deployment-skupper-expose
  annotations:
    github.com/project-slug: backstage-skupper-demo/backstage-catalog
spec:
  type: skupper-expose
  lifecycle: unknown
  owner: Joshua Mathianas
